#!/usr/bin/env python3
"""Snapshot GitHub repo trees into js/demos.js (front-coded, compact).

Usage: python3 tools/make_demos.py owner/repo [owner/repo ...]
Set GITHUB_TOKEN to raise the API rate limit. Pass --from-dir DIR to read
cached <owner>_<repo>.json API responses instead of fetching.
"""
import json, os, sys, urllib.request

def fetch_tree(full):
    req = urllib.request.Request(
        f"https://api.github.com/repos/{full}/git/trees/HEAD?recursive=1",
        headers={"Accept": "application/vnd.github+json", "User-Agent": "filophone-demo-snapshot"})
    tok = os.environ.get("GITHUB_TOKEN")
    if tok:
        req.add_header("Authorization", f"Bearer {tok}")
    with urllib.request.urlopen(req) as r:
        return json.load(r)

def encode(entries):
    # Only files and submodules: git has no empty dirs, folders are implied by paths.
    items = sorted((e for e in entries if e["type"] in ("blob", "commit")), key=lambda e: e["path"])
    out, prev = [], ""
    for e in items:
        p = e["path"]
        n = 0
        while n < min(len(p), len(prev)) and p[n] == prev[n]:
            n += 1
        size = "@" if e["type"] == "commit" else str(e.get("size", 0))
        out.append(f"{n}|{p[n:]}|{size}")
        prev = p
    return "\n".join(out)

def main():
    args = sys.argv[1:]
    src_dir = None
    if "--from-dir" in args:
        i = args.index("--from-dir"); src_dir = args[i + 1]; del args[i:i + 2]
    demos = []
    for full in args:
        if src_dir:
            data = json.load(open(os.path.join(src_dir, full.replace("/", "_") + ".json")))
        else:
            data = fetch_tree(full)
        demos.append({"repo": full, "truncated": bool(data.get("truncated")), "data": encode(data["tree"])})
        print(full, len(data["tree"]), "entries", len(demos[-1]["data"]), "chars", file=sys.stderr)
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, "..", "js", "demos.js"), "w") as f:
        f.write("// Generated by tools/make_demos.py — snapshots of public repo trees (paths + sizes only).\n")
        f.write("// Format per line: <shared prefix length>|<path suffix>|<size in bytes, or @ for a submodule>\n")
        f.write("const DEMOS = " + json.dumps(demos, ensure_ascii=False, separators=(",", ":")).replace("},{", "},\n{") + ";\n")

main()
